name: Docker Image Testbuild

on:
  push:
    branches: []
  pull_request:
    branches: [ master, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the server image
      run: docker build . --file Dockerfile --tag presidents-with-friends-server:build
